import {
  Layers,
  MessageSquare,
  Clock,
  RefreshCw,
  Zap,
  Shield,
  Code2,
  Trash2,
  Sparkles,
  Lock,
  WifiOff,
  ShoppingCart,
  Users,
  User,
  CreditCard,
  Settings,
  Gauge,
  FileDown,
  UserCheck,
} from "lucide-react";
import {
  basicVariants,
  withDescription,
  customDuration,
  promiseToast,
  promiseWithDescription,
  actionToasts,
  cancelToasts,
  customJsxButtons,
  loadingThenSuccess,
  loadingThenError,
  dismissAll,
  updateInPlace,
  customIcons,
  realWorldAuth,
  realWorldNetwork,
  realWorldEcommerce,
  realWorldCollaboration,
  errorWithRetry,
  multiStepSignup,
  multiStepCheckout,
  keyboardHint,
  rateLimitToasts,
  backgroundJob,
  onboardingNudge,
  settingsSaved,
} from "./toast-demos.tsx";

export type Group = {
  id: string;
  label: string;
  tag: string;
  tagColor: string;
  icon: React.ComponentType<{
    className?: string;
    style?: React.CSSProperties;
  }>;
  desc: string;
  actions: { label: string; fn: () => void }[];
};

export const GROUPS: Group[] = [
  {
    id: "01",
    label: "Core Variants",
    tag: "core",
    tagColor: "#94a3b8",
    icon: Layers,
    desc: "The essential foundations for any app including success, error, warning, and informational alerts.",
    actions: [{ label: "Show all variants", fn: basicVariants }],
  },
  {
    id: "02",
    label: "Rich Content",
    tag: "content",
    tagColor: "#60a5fa",
    icon: MessageSquare,
    desc: "Sometimes a title isn't enough. Use descriptions and icons to give your users more context.",
    actions: [{ label: "See an example", fn: withDescription }],
  },
  {
    id: "03",
    label: "Strategic Timing",
    tag: "timing",
    tagColor: "#fbbf24",
    icon: Clock,
    desc: "Control how long a message stays on screen to match how important it is for your user.",
    actions: [{ label: "Test the timing", fn: customDuration }],
  },
  {
    id: "04",
    label: "Async Promises",
    tag: "async",
    tagColor: "#a78bfa",
    icon: RefreshCw,
    desc: "Handle your data fetching states automatically by showing loading, success, and error updates.",
    actions: [
      { label: "Check the flow", fn: promiseToast },
      { label: "Detailed view", fn: promiseWithDescription },
    ],
  },
  {
    id: "05",
    label: "Interactive Actions",
    tag: "interactive",
    tagColor: "#34d399",
    icon: Zap,
    desc: "Let your users take action directly from the notification like retrying or undoing a step.",
    actions: [{ label: "Try it out", fn: actionToasts }],
  },
  {
    id: "06",
    label: "Undo and Cancel",
    tag: "interactive",
    tagColor: "#34d399",
    icon: Shield,
    desc: "Give your users a moment to change their mind before they commit to an important action.",
    actions: [{ label: "Test undo", fn: cancelToasts }],
  },
  {
    id: "07",
    label: "Custom Layouts",
    tag: "custom",
    tagColor: "#f472b6",
    icon: Code2,
    desc: "Build your own notification design using React components when you need something unique.",
    actions: [{ label: "See custom design", fn: customJsxButtons }],
  },
  {
    id: "08",
    label: "Success Flow",
    tag: "control",
    tagColor: "#22d3ee",
    icon: RefreshCw,
    desc: "Watch a loading state smoothly transition into a success message once a task is finished.",
    actions: [{ label: "Simulate task", fn: loadingThenSuccess }],
  },
  {
    id: "09",
    label: "Error Handling",
    tag: "control",
    tagColor: "#22d3ee",
    icon: RefreshCw,
    desc: "See how to handle situations where things don't go as planned after a loading state.",
    actions: [{ label: "Simulate failure", fn: loadingThenError }],
  },
  {
    id: "10",
    label: "Manual Controls",
    tag: "control",
    tagColor: "#22d3ee",
    icon: Trash2,
    desc: "Take full control by manually clearing notifications or resetting the whole stack.",
    actions: [{ label: "Clear everything", fn: dismissAll }],
  },
  {
    id: "11",
    label: "Live Updates",
    tag: "control",
    tagColor: "#22d3ee",
    icon: Layers,
    desc: "Update an existing notification in real time as a background process moves through stages.",
    actions: [{ label: "See live update", fn: updateInPlace }],
  },
  {
    id: "12",
    label: "Visual Identity",
    tag: "visual",
    tagColor: "#facc15",
    icon: Sparkles,
    desc: "Use your own brand icons or custom graphics to make the notifications feel part of your app.",
    actions: [{ label: "Show custom icons", fn: customIcons }],
  },
  {
    id: "13",
    label: "Secure Access",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: Lock,
    desc: "Show reliable updates for login attempts, security codes, and account verifications.",
    actions: [{ label: "Try auth flow", fn: realWorldAuth }],
  },
  {
    id: "14",
    label: "Network Health",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: WifiOff,
    desc: "Let your users know when they go offline or when their data has been safely saved.",
    actions: [{ label: "Test network sync", fn: realWorldNetwork }],
  },
  {
    id: "15",
    label: "Store Events",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: ShoppingCart,
    desc: "Professional alerts for cart updates, successful orders, and payment confirmations.",
    actions: [{ label: "Simulate shop flow", fn: realWorldEcommerce }],
  },
  {
    id: "16",
    label: "Team Activity",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: Users,
    desc: "Keep everyone in the loop with updates on new messages and shared project links.",
    actions: [{ label: "See social updates", fn: realWorldCollaboration }],
  },
  {
    id: "17",
    label: "Intelligent Retry",
    tag: "resilience",
    tagColor: "#f87171",
    icon: RefreshCw,
    desc: "Handle server errors gracefully by offering a simple way to try the action again.",
    actions: [{ label: "Test retry logic", fn: errorWithRetry }],
  },
  {
    id: "18",
    label: "User Onboarding",
    tag: "flow",
    tagColor: "#818cf8",
    icon: User,
    desc: "Deliver a smooth experience for account setup and welcoming new users to your app.",
    actions: [{ label: "Start onboarding", fn: multiStepSignup }],
  },
  {
    id: "19",
    label: "Order Tracking",
    tag: "flow",
    tagColor: "#818cf8",
    icon: CreditCard,
    desc: "Follow a payment through every step of the process from validation to final receipt.",
    actions: [{ label: "Run checkout test", fn: multiStepCheckout }],
  },
  {
    id: "20",
    label: "Profile Settings",
    tag: "utility",
    tagColor: "#fb923c",
    icon: Settings,
    desc: "Quick and unobtrusive confirmation when a user saves their personal preferences.",
    actions: [{ label: "Save settings", fn: settingsSaved }],
  },
  {
    id: "21",
    label: "User Guidance",
    tag: "ux",
    tagColor: "#c084fc",
    icon: Sparkles,
    desc: "Help your users discover helpful keyboard shortcuts and navigation tips naturally.",
    actions: [{ label: "Show shortcuts", fn: keyboardHint }],
  },
  {
    id: "22",
    label: "Usage Limits",
    tag: "system",
    tagColor: "#fb923c",
    icon: Gauge,
    desc: "Politely inform your users when they are approaching their system or API limits.",
    actions: [{ label: "Check limits", fn: rateLimitToasts }],
  },
  {
    id: "23",
    label: "Background Tasks",
    tag: "async",
    tagColor: "#a78bfa",
    icon: FileDown,
    desc: "Keep users informed about the status of exports and long running background jobs.",
    actions: [{ label: "Try background job", fn: backgroundJob }],
  },
  {
    id: "24",
    label: "Engagement",
    tag: "ux",
    tagColor: "#c084fc",
    icon: UserCheck,
    desc: "Encourage users to explore more features by showing helpful tips at the right moment.",
    actions: [{ label: "Show engagement tips", fn: onboardingNudge }],
  },
];
