import {
  Layers,
  MessageSquare,
  Clock,
  RefreshCw,
  Zap,
  Shield,
  Code2,
  Trash2,
  Sparkles,
  Lock,
  WifiOff,
  ShoppingCart,
  Users,
  User,
  CreditCard,
  Settings,
  Gauge,
  FileDown,
  UserCheck,
} from "lucide-react";
import {
  basicVariants,
  withDescription,
  customDuration,
  promiseToast,
  promiseWithDescription,
  actionToasts,
  cancelToasts,
  customJsxButtons,
  loadingThenSuccess,
  loadingThenError,
  dismissAll,
  updateInPlace,
  customIcons,
  realWorldAuth,
  realWorldNetwork,
  realWorldEcommerce,
  realWorldCollaboration,
  errorWithRetry,
  multiStepSignup,
  multiStepCheckout,
  keyboardHint,
  rateLimitToasts,
  backgroundJob,
  onboardingNudge,
  settingsSaved,
} from "./toast-demos.tsx";

export type Group = {
  id: string;
  label: string;
  tag: string;
  tagColor: string;
  icon: React.ComponentType<{
    className?: string;
    style?: React.CSSProperties;
  }>;
  desc: string;
  actions: { label: string; fn: () => void }[];
};

export const GROUPS: Group[] = [
  {
    id: "01",
    label: "Basic Variants",
    tag: "core",
    tagColor: "#94a3b8",
    icon: Layers,
    desc: "The five building blocks every app needs — default, success, error, warning, info.",
    actions: [{ label: "Fire all 5", fn: basicVariants }],
  },
  {
    id: "02",
    label: "Rich Description",
    tag: "content",
    tagColor: "#60a5fa",
    icon: MessageSquare,
    desc: "Supporting text and contextual icons transform a dismissal into a genuine decision.",
    actions: [{ label: "Show", fn: withDescription }],
  },
  {
    id: "03",
    label: "Duration Control",
    tag: "timing",
    tagColor: "#fbbf24",
    icon: Clock,
    desc: "Flash, standard, sticky, extended — match toast lifetime to the urgency of the message.",
    actions: [{ label: "Show", fn: customDuration }],
  },
  {
    id: "04",
    label: "Promise Lifecycle",
    tag: "async",
    tagColor: "#a78bfa",
    icon: RefreshCw,
    desc: "One call manages loading → success | error automatically as your Promise resolves.",
    actions: [
      { label: "Simple callback", fn: promiseToast },
      { label: "With description", fn: promiseWithDescription },
    ],
  },
  {
    id: "05",
    label: "Action Buttons",
    tag: "interactive",
    tagColor: "#34d399",
    icon: Zap,
    desc: "Undo deletes. Retry failures. Update software. Inline CTAs keep users in flow.",
    actions: [{ label: "Show 3 patterns", fn: actionToasts }],
  },
  {
    id: "06",
    label: "Cancel Patterns",
    tag: "interactive",
    tagColor: "#34d399",
    icon: Shield,
    desc: "Abort destructive operations — deletion, logout, bulk remove — before they commit.",
    actions: [{ label: "Show", fn: cancelToasts }],
  },
  {
    id: "07",
    label: "Custom JSX",
    tag: "custom",
    tagColor: "#f472b6",
    icon: Code2,
    desc: "Full React in your action buttons — custom colours, icons, any markup you need.",
    actions: [{ label: "Show", fn: customJsxButtons }],
  },
  {
    id: "08",
    label: "Load → Success",
    tag: "control",
    tagColor: "#22d3ee",
    icon: RefreshCw,
    desc: "Capture a loading toast's id, then morph it to success when the async operation completes.",
    actions: [{ label: "Simulate", fn: loadingThenSuccess }],
  },
  {
    id: "09",
    label: "Load → Error",
    tag: "control",
    tagColor: "#22d3ee",
    icon: RefreshCw,
    desc: "Same id-based pattern resolved to an error state — payment decline, auth failure.",
    actions: [{ label: "Simulate", fn: loadingThenError }],
  },
  {
    id: "10",
    label: "Dismiss & Clear",
    tag: "control",
    tagColor: "#22d3ee",
    icon: Trash2,
    desc: "toast.dismiss() clears one or all — essential for cleanup on navigation or sign-out.",
    actions: [{ label: "Show then clear", fn: dismissAll }],
  },
  {
    id: "11",
    label: "Update in Place",
    tag: "control",
    tagColor: "#22d3ee",
    icon: Layers,
    desc: "Single id, five states — the cleanest way to render a multi-phase deployment pipeline.",
    actions: [{ label: "Deploy flow", fn: updateInPlace }],
  },
  {
    id: "12",
    label: "Custom Icons",
    tag: "visual",
    tagColor: "#facc15",
    icon: Sparkles,
    desc: "Replace default icons with Lucide, emoji, or any React node to match your brand language.",
    actions: [{ label: "Show 6 variants", fn: customIcons }],
  },
  {
    id: "13",
    label: "Auth Flows",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: Lock,
    desc: "Login confirmation, 2FA enabled, suspicious device — auth UX that builds user trust.",
    actions: [{ label: "Simulate", fn: realWorldAuth }],
  },
  {
    id: "14",
    label: "Network Events",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: WifiOff,
    desc: "Offline detection, autosave confirmation — graceful degradation that reassures users.",
    actions: [{ label: "Simulate", fn: realWorldNetwork }],
  },
  {
    id: "15",
    label: "E-commerce",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: ShoppingCart,
    desc: "Plan upgrades, flash sales, refunds — the moments that drive revenue and reduce churn.",
    actions: [{ label: "Simulate", fn: realWorldEcommerce }],
  },
  {
    id: "16",
    label: "Collaboration",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: Users,
    desc: "Co-editing presence, share links, clipboard confirm — Figma-style real-time feedback.",
    actions: [{ label: "Simulate", fn: realWorldCollaboration }],
  },
  {
    id: "17",
    label: "Auto-Retry",
    tag: "resilience",
    tagColor: "#f87171",
    icon: RefreshCw,
    desc: "Exponential backoff with attempt counters — production-grade error recovery pattern.",
    actions: [{ label: "Simulate 3 attempts", fn: errorWithRetry }],
  },
  {
    id: "18",
    label: "Multi-step Signup",
    tag: "flow",
    tagColor: "#818cf8",
    icon: User,
    desc: "Single loading toast walks through validation, creation, workspace setup, email delivery.",
    actions: [{ label: "Run signup", fn: multiStepSignup }],
  },
  {
    id: "19",
    label: "Checkout Pipeline",
    tag: "flow",
    tagColor: "#818cf8",
    icon: CreditCard,
    desc: "Cart → payment → merchant confirm → order confirmed. Four clean states, one toast id.",
    actions: [{ label: "Run checkout", fn: multiStepCheckout }],
  },
  {
    id: "20",
    label: "Settings Saved",
    tag: "utility",
    tagColor: "#fb923c",
    icon: Settings,
    desc: "Autosave confirmation with icon — the highest-frequency toast in any settings-heavy product.",
    actions: [
      {
        label: "Fire",
        fn: settingsSaved,
      },
    ],
  },
  {
    id: "21",
    label: "Keyboard Hints",
    tag: "ux",
    tagColor: "#c084fc",
    icon: Sparkles,
    desc: "Contextual shortcut discovery — surface ⌘K, ⌘Z, ⌘⇧P at the right moment to create power users.",
    actions: [{ label: "Show 3 hints", fn: keyboardHint }],
  },
  {
    id: "22",
    label: "Rate Limit & Quota",
    tag: "system",
    tagColor: "#fb923c",
    icon: Gauge,
    desc: "Warn at 80%, block at 100%, celebrate the refill — the full API quota UX lifecycle.",
    actions: [{ label: "Simulate cycle", fn: rateLimitToasts }],
  },
  {
    id: "23",
    label: "Background Job",
    tag: "async",
    tagColor: "#a78bfa",
    icon: FileDown,
    desc: "Long-running export: fire-and-forget, poll phases, sticky completion with download CTA.",
    actions: [{ label: "Start export", fn: backgroundJob }],
  },
  {
    id: "24",
    label: "Onboarding Nudge",
    tag: "ux",
    tagColor: "#c084fc",
    icon: UserCheck,
    desc: "Profile completion, integration prompts, streak rewards — toasts that turn new users into power users.",
    actions: [{ label: "Show nudges", fn: onboardingNudge }],
  },
];
