import {
  Layers,
  MessageSquare,
  Clock,
  RefreshCw,
  Zap,
  Shield,
  Code2,
  Trash2,
  Sparkles,
  Lock,
  WifiOff,
  ShoppingCart,
  Users,
  User,
  CreditCard,
  Settings,
  Gauge,
  FileDown,
  UserCheck,
} from "lucide-react";
import {
  basicVariants,
  withDescription,
  customDuration,
  promiseToast,
  promiseWithDescription,
  actionToasts,
  cancelToasts,
  customJsxButtons,
  loadingThenSuccess,
  loadingThenError,
  dismissAll,
  updateInPlace,
  customIcons,
  realWorldAuth,
  realWorldNetwork,
  realWorldEcommerce,
  realWorldCollaboration,
  errorWithRetry,
  multiStepSignup,
  multiStepCheckout,
  keyboardHint,
  rateLimitToasts,
  backgroundJob,
  onboardingNudge,
  settingsSaved,
} from "./toast-demos.tsx";

export type Group = {
  id: string;
  label: string;
  tag: string;
  tagColor: string;
  icon: React.ComponentType<{
    className?: string;
    style?: React.CSSProperties;
  }>;
  desc: string;
  actions: { label: string; fn: () => void }[];
};

export const GROUPS: Group[] = [
  {
    id: "01",
    label: "Basic Variants",
    tag: "core",
    tagColor: "#94a3b8",
    icon: Layers,
    desc: "The five essential variants for every application — default, success, error, warning, and info.",
    actions: [{ label: "Fire all 5", fn: basicVariants }],
  },
  {
    id: "02",
    label: "Rich Content",
    tag: "content",
    tagColor: "#60a5fa",
    icon: MessageSquare,
    desc: "Use supporting descriptions and contextual icons to transform notification into clear intent.",
    actions: [{ label: "Show Example", fn: withDescription }],
  },
  {
    id: "03",
    label: "Duration & Timing",
    tag: "timing",
    tagColor: "#fbbf24",
    icon: Clock,
    desc: "Flash, standard, sticky, or extended — match toast lifetime to the urgency of your message.",
    actions: [{ label: "Show Example", fn: customDuration }],
  },
  {
    id: "04",
    label: "Promise Lifecycle",
    tag: "async",
    tagColor: "#a78bfa",
    icon: RefreshCw,
    desc: "Automatically manage transitions through loading, success, and error states as your Promise resolves.",
    actions: [
      { label: "Simple Callback", fn: promiseToast },
      { label: "With Description", fn: promiseWithDescription },
    ],
  },
  {
    id: "05",
    label: "Action Buttons",
    tag: "interactive",
    tagColor: "#34d399",
    icon: Zap,
    desc: "Undo deletions, retry failures, or trigger updates with accessible inline call-to-action buttons.",
    actions: [{ label: "Show 3 Patterns", fn: actionToasts }],
  },
  {
    id: "06",
    label: "Cancel Patterns",
    tag: "interactive",
    tagColor: "#34d399",
    icon: Shield,
    desc: "Provide a safety net for destructive operations — like deletion or logout — before they commit.",
    actions: [{ label: "Show Example", fn: cancelToasts }],
  },
  {
    id: "07",
    label: "Custom JSX",
    tag: "custom",
    tagColor: "#f472b6",
    icon: Code2,
    desc: "Inject rich React components to create highly specialized notification layouts with custom markup.",
    actions: [{ label: "Show Example", fn: customJsxButtons }],
  },
  {
    id: "08",
    label: "Loading to Success",
    tag: "control",
    tagColor: "#22d3ee",
    icon: RefreshCw,
    desc: "Capture a transient loading identity and morph it into a success state once processing completes.",
    actions: [{ label: "Simulate Flow", fn: loadingThenSuccess }],
  },
  {
    id: "09",
    label: "Loading to Error",
    tag: "control",
    tagColor: "#22d3ee",
    icon: RefreshCw,
    desc: "Manually resolve a loading state to an error variant for handling payment failures or auth denials.",
    actions: [{ label: "Simulate Flow", fn: loadingThenError }],
  },
  {
    id: "10",
    label: "Dismiss & Clear",
    tag: "control",
    tagColor: "#22d3ee",
    icon: Trash2,
    desc: "Clear individual notifications or the entire stack — essential for cleanup during navigation.",
    actions: [{ label: "Show Then Clear", fn: dismissAll }],
  },
  {
    id: "11",
    label: "State Mutation",
    tag: "control",
    tagColor: "#22d3ee",
    icon: Layers,
    desc: "Seamlessly update a single toast ID through a multi-phase deployment or processing pipeline.",
    actions: [{ label: "Deploy Flow", fn: updateInPlace }],
  },
  {
    id: "12",
    label: "Custom Icons",
    tag: "visual",
    tagColor: "#facc15",
    icon: Sparkles,
    desc: "Swap default icons for Lucide, emoji, or custom SVG nodes to match your brand's unique language.",
    actions: [{ label: "Show 6 Variants", fn: customIcons }],
  },
  {
    id: "13",
    label: "Auth UX",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: Lock,
    desc: "Login confirmations, 2FA triggers, and suspicious device alerts that build user confidence.",
    actions: [{ label: "Simulate Flow", fn: realWorldAuth }],
  },
  {
    id: "14",
    label: "Network Events",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: WifiOff,
    desc: "Gracefully handle offline detection and autosave confirmations to reassure users during sessions.",
    actions: [{ label: "Simulate Flow", fn: realWorldNetwork }],
  },
  {
    id: "15",
    label: "E-Commerce",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: ShoppingCart,
    desc: "Drive revenue and reduce churn with plan upgrades, flash sale alerts, and refund confirmations.",
    actions: [{ label: "Simulate Flow", fn: realWorldEcommerce }],
  },
  {
    id: "16",
    label: "Collaboration",
    tag: "scenario",
    tagColor: "#2dd4bf",
    icon: Users,
    desc: "Figma-style feedback for presence notifications, share links, and clipboard success events.",
    actions: [{ label: "Simulate Flow", fn: realWorldCollaboration }],
  },
  {
    id: "17",
    label: "Retry Mechanism",
    tag: "resilience",
    tagColor: "#f87171",
    icon: RefreshCw,
    desc: "Production-grade recovery featuring exponential backoff and interactive attempt counters.",
    actions: [{ label: "Simulate 3 Attempts", fn: errorWithRetry }],
  },
  {
    id: "18",
    label: "Onboarding Flow",
    tag: "flow",
    tagColor: "#818cf8",
    icon: User,
    desc: "Guide users through account creation, workspace setup, and verification in a single flow.",
    actions: [{ label: "Run Signup", fn: multiStepSignup }],
  },
  {
    id: "19",
    label: "Checkout Pipeline",
    tag: "flow",
    tagColor: "#818cf8",
    icon: CreditCard,
    desc: "Multi-stage payment tracking from validation to merchant confirmation in a unified toast.",
    actions: [{ label: "Run Checkout", fn: multiStepCheckout }],
  },
  {
    id: "20",
    label: "Settings Saved",
    tag: "utility",
    tagColor: "#fb923c",
    icon: Settings,
    desc: "The standard autosave pattern — high frequency, low friction feedback for modern dashboards.",
    actions: [{ label: "Fire Save", fn: settingsSaved }],
  },
  {
    id: "21",
    label: "Keyboard Hints",
    tag: "ux",
    tagColor: "#c084fc",
    icon: Sparkles,
    desc: "Enhance power-user discovery by surfacing shortcut hints like ⌘K at the perfect precise moment.",
    actions: [{ label: "Show 3 Hints", fn: keyboardHint }],
  },
  {
    id: "22",
    label: "Rate Limiting",
    tag: "system",
    tagColor: "#fb923c",
    icon: Gauge,
    desc: "Warn at thresholds, block on overflow, and celebrate refill — the complete API lifecycle.",
    actions: [{ label: "Simulate Cycle", fn: rateLimitToasts }],
  },
  {
    id: "23",
    label: "Long-Running Jobs",
    tag: "async",
    tagColor: "#a78bfa",
    icon: FileDown,
    desc: "Manage background exports with fire-and-forget polling, progress updates, and final download CTAs.",
    actions: [{ label: "Start Export", fn: backgroundJob }],
  },
  {
    id: "24",
    label: "Conversion Nudges",
    tag: "ux",
    tagColor: "#c084fc",
    icon: UserCheck,
    desc: "Drive growth with profile completion prompts, integration nudges, and behavioral rewards.",
    actions: [{ label: "Show Nudges", fn: onboardingNudge }],
  },
];
